# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wordle < Formula
  desc "Play wordle in cli"
  homepage "https://github.com/ashish336b/homebrew-wordle"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.17/wordle_0.0.17_Darwin_x86_64.tar.gz"
      sha256 "5b97511d368f56ab0ac4480de9ee29cbef3541a7dcee9645d75ca2b1558a7783"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.17/wordle_0.0.17_Darwin_arm64.tar.gz"
      sha256 "25a0cdbb8e35999062dbca68e60bd097c6f2947ddfb8544a7f876876eb8c63a8"

      def install
        bin.install "wordle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.17/wordle_0.0.17_Linux_arm64.tar.gz"
      sha256 "2ce1ec2c3b5249ed8413299fbcebd65b73bb3abd8c2e0c1ccdee9f20952a2793"

      def install
        bin.install "wordle"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ashish336b/wordle/releases/download/v0.0.17/wordle_0.0.17_Linux_x86_64.tar.gz"
      sha256 "b4c11757ce54c8f9101c0bd0e0cfac0078cda08080200182292ac4c05b755ce6"

      def install
        bin.install "wordle"
      end
    end
  end
end
